name: Update Builtins

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-builtins:
    name: Update Builtins
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push changes

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update builtins
        run: |
          ./gen_builtins.sh

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update builtins"
          git push

      - name: Trigger release workflow
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          echo "Builtins updated - release workflow will be triggered by the push to master"
